import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProviders from "@/providers/toast";
import { ThemeProvider } from "@/providers/theme";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { SettingModal } from "@/providers/settingModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
          </ThemeProvider>
        <ToastProviders />
        <SettingModal />
        </body>
      </html>
    </SessionProvider>
  );
}
